baseurl = "http://test2.rchapman.org/"
title = "Ryan A. Chapman"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Ryan A. Chapman"
googleAnalytics = "XXX"
disqusShortname = "blog-rchapman-org"

[Author]
    name = "Ryan A. Chapman"
    profile = "https://google.com/+XXX"

[Taxonomies]
    tag = "tags"

[Params]
    intro = false
    headline = "blog.rchapman.org"
    description = ""
    github = "https://github.com/ryanchapman"
    linkedin = "https://linkedin.com/in/ryanachapman/"
    gplus = "https://plus.google.com/u/0/116175235833210820781"
    twitter = "https://twitter.com/ryanchapman"
    blogsource = "https://github.com/ryanchapman/test2"
#    stackoverflow = "http://stackoverflow.com/users/XXX/YYY"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Latest Post"
    url = "/posts/latest"
    weight = 1

[[menu.main]]
    name = "Browse Posts"
    url = "/posts"
    weight = 2

#[[menu.main]]
#    name = "Projects"
#    url = "/project/"
#    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 4

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 5
